Jd 1351 to myteam
mailru/jira-plugins-mrimsender pull request #45
Opened 2021-02-09 12:20 UTC by Bezneima

add MyteamServerErrorException

2021-02-09 12:39 UTC, Raschudesny requested changes

2021-02-09 12:39 UTC, Raschudesny commented on src/main/java/ru/mail/jira/plugins/myteam/myteam/MyteamApiClientImpl.java
> +    } catch (MyteamServerErrorException myteamServerErrorException) {
Двумя строчками выше кинули свой кастомный экспешн, двумя строчками ниже поймали его чтобы залогировать ? :)

2021-02-09 12:39 UTC, Raschudesny commented on src/main/java/ru/mail/jira/plugins/myteam/configuration/ThirdPartyServiceInitializer.java
> +            return null;
А вот это как-то грустно скорее :( 
Типа теперь придется вместо того чтобы запрос падал с RuntimeException каждый раз когда asObject не понял что ему пришло. Проверять прямо в методах которые работают с клиентами, что у них в HttpResponse<null> на самом деле может лежать.... @mashintsev  оно прямо точно так надо?

2021-02-09 12:39 UTC, Raschudesny commented on src/main/java/ru/mail/jira/plugins/myteam/myteam/MyteamApiClientImpl.java
> +    } catch (MyteamServerErrorException myteamServerErrorException) {
Ну короче вот так как-то наверное лучше  делать

```
if (response ....) {
Exception newExc = new MyteamServerErrorException(response.getStatus(), response.getRawBody().toString())
log("exception occurred bla bla", newExc)
throw newExc
}
```
И тогда не придется никаких return null тут выдумывать и проверять на них потом сверху ещё :) 

А касаемо логирование то можно вообще оставить ответственность за логирование всех возможных ошибок MyteamServerErrorException под отвественность вызывающего метод, чтобы типа кто вызвал sendMessageText и у кого он упал с ошибкой тот и логирует.

2021-02-10 08:10 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/myteam/MyteamApiClientImpl.java
> +    if (response.getStatus() >= 500 || response.getStatus() < 600) {
добавить проверку response.getBody на null

2021-02-10 08:15 UTC, mashintsev approved these changes

2021-02-10 08:15 UTC, merged