JD-1374 to myteam
mailru/jira-plugins-mrimsender pull request #51
Opened 2021-02-24 16:34 UTC by Bezneima

add myTeam chat members avatarGroup into panel

2021-02-24 19:31 UTC, mashintsev requested changes

2021-02-24 19:31 UTC, mashintsev commented on js/src/create-chat-panel/stores/LoadingService.tsx
> +  avatarUrl:string,
нужно сделать форматирование всех измененных файлов

2021-02-24 19:31 UTC, mashintsev commented on js/src/create-chat-panel/views/ChatInfo.tsx
> +const MyteamImage = require('../../assets/myteam.png');
зачем тут require? тоже самое через import можно сделать

2021-02-24 19:31 UTC, mashintsev commented on js/src/create-chat-panel/views/ChatInfo.tsx
> +    padding-left:5px;
можно ненужных стилей

2021-02-24 19:31 UTC, mashintsev commented on js/src/create-chat-panel/views/ChatInfo.tsx
> +            avatarUrl: member.avatarUrl,
почему бы с сервера сразу такую структуру не присылать?

2021-02-24 19:31 UTC, mashintsev commented on js/src/create-chat-panel/views/ChatInfo.tsx
> +                <dl>
какие то лишние dl

2021-02-24 19:31 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/myteam/MyteamApiClient.java
> +  HttpResponse<ChatMember> getMembersWithoutCursor(@Nonnull String chatId) throws UnirestException;
WithoutCursor ??? это к чему вообще?

2021-02-24 19:31 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/rest/ChatCreationService.java
> +        if (chatMetaDto != null) chatMetaDto.setMembers(chatMemberDtos);
зачем тут проверка на null?

2021-02-24 19:31 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/rest/dto/ChatMetaDto.java
> +@RequiredArgsConstructor
Зачем тут изменена аннотация?

2021-02-24 19:57 UTC, Raschudesny commented on js/src/create-chat-panel/views/ChatInfo.tsx
> +const MyteamImage = require('../../assets/myteam.png');
Сори, это ещё от меня осталось :) 
Надо поменять строчку с реквайром на 
import MyteamImage from '../../assets/myteam.png';
И в файле jira.d.ts дописать строку 
declare module '*.png';

Ну и соответственно само обращение к картинке должно теперь выглядеть вот так
<img height={gridSize() * 2.5} src={MyteamImage} ... 
без всяких MyteamImage.default

2021-02-25 12:24 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/rest/dto/ChatMetaDto.java
> +@RequiredArgsConstructor
для того чтобы не создавался конструктор на все поля тк я добавил поле которое можно было бы не заполнять. вернул обратно

2021-02-25 12:25 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/rest/ChatCreationService.java
> +        if (chatMetaDto != null) chatMetaDto.setMembers(chatMemberDtos);
тк buildChatInfo мог выдавать null но из-за того что я вернул старую аннотацию @AllArgsConstructor теперь заполняется участниками при создании chatMetaDto

2021-02-25 12:28 UTC, merged

2021-02-25 12:29 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/myteam/MyteamApiClient.java
> +  HttpResponse<ChatMember> getMembersWithoutCursor(@Nonnull String chatId) throws UnirestException;
потому что через апи пользователей можно получить при помощи курсора и количество людей в апи не указано сколько выдается на 1 странице и поэтому я решил что скорее всего это для того чтобы если количество участников будет больше чем возможно записать и передать через 1 http запрос. Я подумал что врятли столько людей будет когда-нибудь в наших чатах и даже если будет то нет смысла вроде как отображать всех в avatargroup