JD-1506 to myteam
mailru/jira-plugins-mrimsender pull request #54
Opened 2021-05-24 15:53 UTC by Bezneima

Add markdown for issue link

2021-05-24 16:58 UTC, mashintsev requested changes

2021-05-24 16:58 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                            + issue.getKey()
тут вообще не нужен join. Обычная конкатенация подойдет

2021-05-24 16:58 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +    sb.append("[").append(issue.getKey()).append("](").append(issueLink).append(")\n");
Стоить сделать фукнцию которая форматирует ссылки. Тогда не нужно будет повторять эти блоки с скобками

2021-05-24 17:00 UTC, mashintsev requested changes

2021-05-24 17:00 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/myteam/myteam.properties
>  ru.mail.jira.plugins.myteam.notification.closed={0} closed an issue as {2} [ {1} ]
а остальные события?

2021-05-24 17:00 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/myteam/myteam.properties
>  ru.mail.jira.plugins.myteam.notification.closed={0} closed an issue as {2} [ {1} ]
Нужно все события переделать на линк внутри макдаун

2021-05-26 12:33 UTC, mashintsev requested changes

2021-05-26 12:33 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String markdownIssueLink(String issueKey, String issueLink) {
назвать markdownTextLink

2021-05-26 12:33 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                applicationProperties.getString(APKeys.JIRA_BASEURL), issue.getKey()));
почему тут не используется функция createIssueLink ?

2021-05-26 12:33 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +        .append('\n');
и тут createIssueLink ?

2021-05-26 12:33 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                        issue.getSummary()))
так зачем тут join?

2021-05-26 12:33 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                            + ") ",
есть уже функция для формирования ссылки

2021-05-26 12:33 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/myteam/myteam_ru.properties
>  ru.mail.jira.plugins.myteam.notification.closed={0} \u0437\u0430\u043A\u0440\u044B\u043B \u0437\u0430\u043F\u0440\u043E\u0441 \u043A\u0430\u043A {2} [ {1} ]
тут не все сообщения исправлены для ссылок

2021-05-26 12:41 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String markdownIssueLink(String issueKey, String issueLink) {
Изменил

2021-05-26 12:41 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                applicationProperties.getString(APKeys.JIRA_BASEURL), issue.getKey()));
Изменил с использованием createIssueLink

2021-05-26 12:41 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +        .append('\n');
Добавил createIssueLink

2021-05-26 13:05 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/myteam/myteam_ru.properties
>  ru.mail.jira.plugins.myteam.notification.closed={0} \u0437\u0430\u043A\u0440\u044B\u043B \u0437\u0430\u043F\u0440\u043E\u0441 \u043A\u0430\u043A {2} [ {1} ]
Исправил

2021-05-26 13:06 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                            + ") ",
Изменил на createIssueLink

2021-05-26 13:06 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                        issue.getSummary()))
Убрал

2021-05-26 13:07 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +        .append('\n');
Заменил

2021-05-26 13:07 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +                applicationProperties.getString(APKeys.JIRA_BASEURL), issue.getKey()));
заменил

2021-05-26 13:07 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String markdownIssueLink(String issueKey, String issueLink) {
Переименовал

2021-05-26 19:37 UTC, mashintsev approved these changes

2021-07-08 07:57 UTC, mashintsev requested changes

2021-07-08 07:57 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +        return "@\\[" + user.getEmailAddress() + "\\]";
тут сделать как в других коммитах через текстовую ссылку

2021-07-08 07:58 UTC, mashintsev requested changes

2021-07-08 07:58 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
>        return user.getDisplayName() + " (" + user.getEmailAddress() + ")";
тут тоже с текстовой ссылкой

2021-07-08 12:26 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +        return "@\\[" + user.getEmailAddress() + "\\]";
заменил на 
"["
            + user.getName()
            + "](https://u.internal.myteam.mail.ru/profile/"
            + user.getEmailAddress()
            + ")";

2021-07-08 12:26 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
>        return user.getDisplayName() + " (" + user.getEmailAddress() + ")";
"["
            + user.getName()
            + "](https://u.internal.myteam.mail.ru/profile/"
            + user.getEmailAddress()
            + ")";

2021-07-08 15:16 UTC, mashintsev approved these changes

2021-07-08 15:16 UTC, merged