Jd 1544 to myteam
mailru/jira-plugins-mrimsender pull request #57
Opened 2021-07-05 08:58 UTC by Bezneima

Test

2021-07-08 07:49 UTC, mashintsev requested changes

2021-07-08 07:49 UTC, mashintsev commented on src/main/resources/ru/mail/jira/plugins/myteam/myteam.properties
> +ru.mail.jira.plugins.myteam.bitbucket.notification.pr.ending.e=
что это за пустые строки?

2021-07-08 07:49 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +      }
откуда тут опять магия с append и if? + какие непонятные локали ru.mail.jira.plugins.myteam.notification.only.rus.ending.y.

2021-07-12 14:28 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +      }
Убрал все окончания и почти все ифы

2021-07-12 14:28 UTC, Bezneima commented on src/main/resources/ru/mail/jira/plugins/myteam/myteam.properties
> +ru.mail.jira.plugins.myteam.bitbucket.notification.pr.ending.e=
Это были окончания - убрал их

2021-07-12 14:51 UTC, mashintsev requested changes

2021-07-12 14:51 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +              .append(")");
почему тут не используется функция?

2021-07-12 14:51 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +      boolean counter = false;
плохая практика использовать такую переменную, переделай на stream c map и join

2021-07-12 14:51 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +      boolean counter = false;
тут и в других foreach подобных циклах

2021-07-12 14:51 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +    return String.join(
совсем непонятно зачем использовать join тут

2021-07-12 14:51 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +    return String.join(
это же текстовая ссылка, и есть функция для этого

2021-07-13 15:13 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +    return String.join(
Убрал из таких функций string.join и []()

2021-07-13 15:15 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +    return String.join(
я думал что в java + перегружается от конкат а не от stringBuilder поэтому думал что правельнее делать через string.join

2021-07-13 15:16 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +      boolean counter = false;
других вроде нет

2021-07-13 15:17 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +              .append(")");
изменил

2021-07-14 19:25 UTC, merged