JD-1641 to master
mailru/jira-plugins-mrimsender pull request #63
Opened 2021-09-08 17:18 UTC by Bezneima

convert from jira markdown to myteam markdown

2021-09-08 19:50 UTC, mashintsev requested changes

2021-09-08 19:50 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/JiraMarkDownConverter.java
> +public interface JiraMarkDownConverter {
Не нужный класс. Можно использовать интерфейс Function c таким же успехом

2021-09-08 19:50 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String conventToMyteamMarkdown(
опечатка в названии функции

2021-09-08 19:50 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String conventToMyteamMarkdown(
Назвать просто convertToMarkdown

2021-09-08 19:50 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +        Pattern.compile("\\{code:([a-z]+?)\\}([^+]*?)\\{code\\}", Pattern.MULTILINE);
сгруппировать Pattern и места их использования. Сейчас нужно бегать между строчками, чтобы понять где какой применяется

2021-09-08 19:50 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +    inputText = conventToMyteamMarkdown(inputText, markedAsterisk, input -> "*");
так нужно делать и для остальных символов

2021-09-09 11:16 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/JiraMarkDownConverter.java
> +public interface JiraMarkDownConverter {
Заменил на Function

2021-09-09 11:16 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String conventToMyteamMarkdown(
переименовал

2021-09-09 11:17 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +        Pattern.compile("\\{code:([a-z]+?)\\}([^+]*?)\\{code\\}", Pattern.MULTILINE);
вставил их прям туда где применяются, выше поставил комментарий о чем идет изменение в данной строчке

2021-09-09 11:17 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +    inputText = conventToMyteamMarkdown(inputText, markedAsterisk, input -> "*");
сделал для всех символов

2021-09-10 12:09 UTC, mashintsev requested changes

2021-09-10 12:09 UTC, mashintsev commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String makeMyteamMarkdownFromJira(String inputText, boolean useMentionFormat) {
Написать unit test для этого методы.

2021-09-13 13:50 UTC, Bezneima commented on src/main/java/ru/mail/jira/plugins/myteam/protocol/MessageFormatter.java
> +  private String makeMyteamMarkdownFromJira(String inputText, boolean useMentionFormat) {
написал

2021-09-13 13:58 UTC, merged